### ISSUE TITLE
Integration with newer versions of Python

### ISSUE THREAD

**Issue by Pavel-Sushko** [cisagov/untitledgoosetool#10]
# 💡 Summary #

Allow for using of newer python versions.

## Motivation and context ##

Python 3.9 is an old version of Python, and isn't recommended by Python.

This would be useful because...

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Can be installed and run with Python >=3.10

**Comment by victoriawallace-cisa** [comment]
We're currently looking into this.

**Comment by victoriawallace-cisa** [comment]
@Pavel-Sushko This feature has been implemented in the latest update. Please grab the latest version of the tool and try it out with Python 3.10.

**Comment by victoriawallace-cisa** [comment]
There was an issue with some dependencies when upgrading to versions of Python > 3.10, so right now, we're only able to support 3.10 as the latest Python version.

**Comment by Pavel-Sushko** [comment]
Just tried with Python 3.10.11, and it doesn't work. It's saying I need to downgrade to Python 3.10.10.
