### ISSUE TITLE
Issue Installing

### ISSUE THREAD

**Issue by RP5406** [cisagov/untitledgoosetool#12]
# 🐛 Summary #

Created a venv in Ubuntu
Python version 3.9
Run: 
git clone https://github.com/cisagov/untitledgoosetool.git
cd untitledgoosetool
python3 -m pip install .

## To reproduce ##

1. Followed steps from Readme

## Expected behavior ##

I expected it to install correctly

## Any helpful log output or screenshots ##

Paste the results here:

`
Collecting wxpython>=4.1.0

  Using cached wxPython-4.2.0.tar.gz (71.0 MB)

  Preparing metadata (setup.py) ... error

  error: subprocess-exited-with-error
  
  × python setup.py egg_info did not run successfully.

  │ exit code: 1

  ╰─> [8 lines of output]

      Traceback (most recent call last):

        File "<string>", line 2, in <module>

        File "<pip-setuptools-caller>", line 34, in <module>

        File "/tmp/pip-install-os4pyg1i/wxpython_d8f1733a99b0422c8299407a793e8a54/setup.py", line 27, in <module>

          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName

        File "/tmp/pip-install-os4pyg1i/wxpython_d8f1733a99b0422c8299407a793e8a54/buildtools/config.py", line 30, in <module>

          from attrdict import AttrDict

      ModuleNotFoundError: No module named 'attrdict'

      [end of output]

  note: This error originates from a subprocess, and is likely not a problem with pip.

error: metadata-generation-failed

× Encountered error while generating package metadata.

╰─> See above for output.

note: This is an issue with the

`

Add any screenshots of the problem here.

**Comment by victoriawallace-cisa** [comment]
Can you try `pip install attrdict` and try to pip install the tool again?

**Comment by RP5406** [comment]
I installed attrdict and then ran 
git clone https://github.com/cisagov/untitledgoosetool.git
cd untitledgoosetool
python3 -m pip install .

Output:
` DEPRECATION: wxpython is being installed using the legacy 'setup.py install' method, because it does not have a 'pyproject.toml' and the 'wheel' package is not installed. pip 23.1 will enforce this behaviour change. A possible replacement is to enable the '--use-pep517' option. Discussion can be found at https://github.com/pypa/pip/issues/8559

  Running setup.py install for wxpython ... error

  error: subprocess-exited-with-error

 
  × Running setup.py install for wxpython did not run successfully.`

**Comment by victoriawallace-cisa** [comment]
It looks like its an issue related to wxpython: https://github.com/wxWidgets/Phoenix/issues/2225

Maybe try pip installing attrdict3?

**Comment by RP5406** [comment]
checking pkg-config is at least version 0.16... yes

      checking for GTK+ - version >= 3.0.0... Package gtk+-3.0 was not found in the pkg-config search path.

      Perhaps you should add the directory containing `gtk+-3.0.pc'

      to the PKG_CONFIG_PATH environment variable

      No package 'gtk+-3.0' found

      no

      *** Could not run GTK+ test program, checking why...

      *** The test program failed to compile or link. See the file config.log for the

      *** exact error that occurred. This usually means GTK+ is incorrectly installed.

      configure: error:

      The development files for GTK+ were not found. For GTK+ 2, please

      ensure that pkg-config is in the path and that gtk+-2.0.pc is

      installed. For GTK+ 1.2 please check that gtk-config is in the path,

      and that the version is 1.2.3 or above. Also check that the

      libraries returned by 'pkg-config gtk+-2.0 --libs' or 'gtk-config

      --libs' are in the LD_LIBRARY_PATH or equivalent.

      

      Error running configure

      ERROR: failed building wxWidgets

      Traceback (most recent call last):

        File "/tmp/pip-install-mxaz5gyf/wxpython_17706fd723854a04bdeab1279abc53f0/build.py", line 1563, in cmd_build_wx

          wxbuild.main(wxDir(), build_options)

        File "/tmp/pip-install-mxaz5gyf/wxpython_17706fd723854a04bdeab1279abc53f0/buildtools/build_wxwidgets.py", line 379, in main

          exitIfError(wxBuilder.configure(dir=wxRootDir, options=configure_opts),

        File "/tmp/pip-install-mxaz5gyf/wxpython_17706fd723854a04bdeab1279abc53f0/buildtools/build_wxwidgets.py", line 72, in exitIfError

          raise builder.BuildError(msg)

      buildtools.builder.BuildError: Error running configure

      Finished command: build_wx (0m2.152s)

      Finished command: build (0m2.152s)

      Command '"/home/red/.venv/bin/python3" -u build.py build' failed with exit code 1.

      [end of output]

  

  note: This error originates from a subprocess, and is likely not a problem with pip.

error: legacy-install-failure



× Encountered error while trying to install package.

╰─> wxpython

**Comment by victoriawallace-cisa** [comment]
What version of Ubuntu are you running?

**Comment by RP5406** [comment]
Distributor ID:	Ubuntu
Description:	Ubuntu 22.04.2 LTS
Release:	22.04
Codename:	jammy

**Comment by RP5406** [comment]
I will spin up a 22.10 and retry

**Comment by RP5406** [comment]
Same issue with 22.10
You can close this out.

**Comment by clairecasalnova-cisa** [comment]
We are currently working to recreate and fix this issue.

**Comment by clairecasalnova-cisa** [comment]
I was able to recreate this issue and find a solution on Ubuntu 22.04 and Python3.9.
1. Ensure that pip is running from your python3.9 version rather than python3.10
2. You will need to manually download the ubuntu wheel for wxPython 
`wget https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/wxPython-4.2.0-cp39-cp39-linux_x86_64.whl`
3. Install the wheel 
`pip install wxPython-4.2.0-cp39-cp39-linux_x86_64.whl`
4. Install tkinter
`sudo apt install python3.9-tk`
5. Install goose
`python -m pip install .`

Hopefully that fixes your issue. Let me know if you have any more issues.

**Comment by victoriawallace-cisa** [comment]
Also, please let us know if that fixes your issue so we can update the readme.

**Comment by RP5406** [comment]
I am going to test that out right now.

**Comment by RP5406** [comment]
Yes that worked following the additional steps @clairecasalnova-cisa provided. 
I was able to run the generate_conf.py and generate the .conf file

Thank you!

**Comment by clairecasalnova-cisa** [comment]
Were you able to successfully run `goosey auth` and `goosey honk` ?

**Comment by RP5406** [comment]
Yes, I ran goosey auth and was able to authenticate and goosey honk as well. I never got any kind of output.

**Comment by clairecasalnova-cisa** [comment]
Did you fill out the entirety of the auth section of the conf file including the app id and client secret and set the calls you were interested in to true? If so, could you provide the output from running honk

**Comment by RP5406** [comment]
Yes, I filled out the auth section as I had to approve the login with my MFA app. I had calls set to True. I will try to test this again later.

**Comment by W00glin** [comment]
> I was able to recreate this issue and find a solution on Ubuntu 22.04 and Python3.9.
> 
>     1. Ensure that pip is running from your python3.9 version rather than python3.10
> 
>     2. You will need to manually download the ubuntu wheel for wxPython
>        `wget https://extras.wxpython.org/wxPython4/extras/linux/gtk3/ubuntu-22.04/wxPython-4.2.0-cp39-cp39-linux_x86_64.whl`
> 
>     3. Install the wheel
>        `pip install wxPython-4.2.0-cp39-cp39-linux_x86_64.whl`
> 
>     4. Install tkinter
>        `sudo apt install python3.9-tk`
> 
>     5. Install goose
>        `python -m pip install .`
> 
> 
> Hopefully that fixes your issue. Let me know if you have any more issues.

Ran into similar if not identical issues a few days ago. Only difference is that I am running on Pop!_OS 22.04 LTS

The above commands go to me to a point where I was able to run `python -m pip install`. Then I ran `python3 scripts/generate_conf.py` and it appears to have executed without issues but I'm not seeing either of the config files in the directory. 

Re-ran the script as `sudo` and it output the following error -

```
Traceback (most recent call last):
  File "/opt/untitledgoosetool/scripts/generate_conf.py", line 8, in <module>
    from goosey.azure_ad_datadumper import AzureAdDataDumper
ModuleNotFoundError: No module named 'goosey'
```

Then I ran `pip list | grep goosey` and it looks like its installed (version 1.0.0).  So `goosey` does appeared to be installed, so not sure why the script is having issues trying to use it.

**Comment by clairecasalnova-cisa** [comment]
@W00glin The configuration files are hidden files. Make sure that you can show hidden files in your file browser GUI or run an `ls -la` to see hidden files.  The files are `.conf` for general configuration and `.d4iot_conf` for Defender for IoT configuration setup. You should not need sudo to install goosey. 
Depending on where you are running the `generate_conf.py` from, your `.conf` could be in either the main goose folder or within the scripts folder.

**Comment by W00glin** [comment]
@clairecasalnova-cisa I was literally only running `ll`. I see them now. Thanks!

**Comment by victoriawallace-cisa** [comment]
@RP5406 We've added the fix to the Installing section of the readme.
