### ISSUE TITLE
Support Number Matching MFA

### ISSUE THREAD

**Issue by TheeMadWhiteHatter** [cisagov/untitledgoosetool#13]
# 💡 Summary #

To allow number matching MFA prompts for Microsoft Authenticator for tool auth

## Motivation and context ##

Without that ability, this tool will not be able to authenticate with any MFA environments in May as MFA for M365 will require number matching.

"Number matching is a key security upgrade to traditional second factor notifications in Microsoft Authenticator. We will remove the admin controls and enforce the number match experience tenant-wide for all users of Microsoft Authenticator push notifications starting May 8, 2023.
We highly recommend enabling number matching in the near term for improved sign-in security. Relevant services will begin deploying these changes after May 8, 2023 and users will start to see number match in approval requests. As services deploy, some may see number match while others don't. To ensure consistent behavior for all users, we highly recommend you enable number match for Microsoft Authenticator push notifications in advance."
https://learn.microsoft.com/en-us/azure/active-directory/authentication/how-to-mfa-number-match

## Implementation notes ##

Allow for a text display (CLI) or pop-up box (GUI) of the numbers to be matched in the authenticator app on the device running the tool. 

## Acceptance criteria ##

How do we know when this work is done?

- Able to use number matching MFA with Microsoft Authenticator.

**Comment by victoriawallace-cisa** [comment]
Thank you for submitting this feature request. We'll look into it.

**Comment by kgoode517** [comment]
Having this issue right now. Cannot proceed with using the tool without the number.

**Comment by victoriawallace-cisa** [comment]
@ogowen45 We've implemented the number matching MFA, why don't you give it a test and let us know how it is?
