### ISSUE TITLE
New Issue, Goosey trying to execute a .exe with python and i cant make the gui version of the tool work.

### ISSUE THREAD

**Issue by thebrainiak** [cisagov/untitledgoosetool#17]
# 🐛 Summary #

When i configure the config file, and i click Start to start to extract logs with the goose-gui, it gives me the error that it doesnt find the goose-gui file in the directory .venv\Scripts\goosey-gui. I think its because the tool is trying to open a .exe with python, how can i solve it? or its a native bug? Its crazy, cause when i use the DIR command in cmd, it shows me a .exe, but when i open the directly in windows gui its a python file.  (And the problem is not the language of the name of the directory of the desktop, cause i have the same error using english language)

1. I configure the config file
1. I click at Start

## Expected behavior ##

Extract the logs and create the file.

## Any helpful log output or screenshots ##
![gosseyerror2](https://user-images.githubusercontent.com/101867702/228958821-b247180c-50c7-4f61-b0dc-3f42c25261b5.png)
![gosseyerror3](https://user-images.githubusercontent.com/101867702/228958835-50a146f6-493a-4b86-80cc-954d9dd91791.png)

![gooseerror](https://user-images.githubusercontent.com/101867702/228956098-174f91f0-16e9-430d-b173-1a3eb51d1bf9.png)

@victoriawallace-cisa @h-m-f-t @sangling

**Comment by victoriawallace-cisa** [comment]
Thanks, I'll take a look at replicating the issue. It looks like you installed Python using the Microsoft store, so I should be able to replicate it soon.

**Comment by victoriawallace-cisa** [comment]
It looks like its an error with the gooey python module and Windows. Here's how to fix it:

1. Download the Gooey source code from here: https://github.com/chriskiehl/Gooey/archive/refs/tags/1.0.8.1.zip
2. Extract the .zip.
3. Open the following file in a text editor: `gooey/gooey/gui/cli.py`
4. Replace the file with the following code:
```
import sys

from itertools import chain

from copy import deepcopy

from gooey.util.functional import compact


def buildCliString(target, cmd, positional, optional, suppress_gooey_flag=False):
    positionals = deepcopy(positional)
    if positionals:
        positionals.insert(0, "--")

    cmd_string = ' '.join(compact(chain(optional, positionals)))

    if cmd != '::gooey/default':
        cmd_string = u'{} {}'.format(cmd, cmd_string)

    ignore_flag = '' if suppress_gooey_flag else '--ignore-gooey'
    if sys.platform == 'win32':
        return u'{}-script.py {} {}'.format(target, ignore_flag, cmd_string)
    else:
        return u'{} {} {}'.format(target, ignore_flag, cmd_string)
```
5. In the Gooey folder, run a `python -m pip install .` (Make sure you are in the folder for the Gooey module).
6. Re-install the untitledgoosetool as well `python -m pip install .` or `python3 -m pip install .`
7. Run `goosey-gui`

Please let us know if that fixes the issue.

**Comment by victoriawallace-cisa** [comment]
@thebrainiak We've fixed the issue in the latest update of Untitled Goose Tool. Please update the tool, re-install it, and try it again and let us know how it goes.
