### ISSUE TITLE
Add to the README that you need C++ Redistributable to make the tool working 

### ISSUE THREAD

**Issue by thebrainiak** [cisagov/untitledgoosetool#18]
# 💡 Summary #

You should add that you need C++ Redistributable to make the tool working at the README, the readme its for specify all the details and i spend one day trying to make it work finding that i need C++ installed.. And check my other issue, because the gui doesnot work. Thank you!

**Comment by victoriawallace-cisa** [comment]
We can add this to the readme in a future update.

**Comment by victoriawallace-cisa** [comment]
Addressed in #28
