### ISSUE TITLE
Add for Smart watch 

### ISSUE THREAD

**Issue by Rexblk81** [cisagov/untitledgoosetool#22]
# 💡 Summary #

What is the work, as a high-level summary?

## Motivation and context ##

Why does this work belong in this project?

This would be useful because...

## Implementation notes ##

Please provide details for implementation, such as:

- an example for how this would be used
- what this would look like
- how this would act
- any related work, including links to related issues

## Acceptance criteria ##

How do we know when this work is done?

- [x] Criterion

**Comment by victoriawallace-cisa** [comment]
Hello, what are you requesting? What do you mean by "Add for Smart watch"?

**Comment by Rexblk81** [comment]
A User interface for a asset for DrapaNet NSA tactical android.

**Comment by victoriawallace-cisa** [comment]
We won't be incorporating this feature request.
