### ISSUE TITLE
Add to Smart watch for updates 

### ISSUE THREAD

**Issue by Rexblk81** [cisagov/untitledgoosetool#23]
# 💡 Summary #

What is the work, as a high-level summary?

## Motivation and context ##

Why does this work belong in this project?

This would be useful because...

## Implementation notes ##

Please provide details for implementation, such as:

- an example for how this would be used
- what this would look like
- how this would act
- any related work, including links to related issues

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Criterion

**Comment by victoriawallace-cisa** [comment]
Duplicate of #22
