### ISSUE TITLE
Error installing tool via pip - "goosey required Python version: 3.10.11"

### ISSUE THREAD

**Issue by tmaiorca** [cisagov/untitledgoosetool#25]
As per the requirements [tool's prerequisites](https://github.com/cisagov/untitledgoosetool#prerequisites):

- Python 3.7, 3.8, 3.9, or 3.10 is required to run Untitled Goose Tool with Python.

With Python 3.9 or 3.10 installed and running in a virtual environment, I'm receiving the following error on Windows 11 when installing via `python3 -m pip install . ` :
`ERROR: Package 'goosey' requires a different Python: 3.10.11 not in '<=3.10.10,>=3.7'`

Attempted Python versions:

- 3.9.13
- 3.10.9
- 3.10.11

![image](https://user-images.githubusercontent.com/46833258/231824666-ac173bd8-2326-4966-9a2c-e4216b06a14f.png)

**Comment by victoriawallace-cisa** [comment]
The readme needs to be updated with Python 3.7, 3.8, 3.9, or 3.10 (3.10.10 is the last supported version).

Are you able to show me the output of when you are running Python version 3.9.13 or 3.10.9? Run `python3 --version` and then `python3 -m pip install .` and show me the output.

**Comment by tmaiorca** [comment]
> The readme needs to be updated with Python 3.7, 3.8, 3.9, or 3.10 (3.10.10 is the last supported version).
> 
> Are you able to show me the output of when you are running Python version 3.9.13 or 3.10.9? Run `python3 --version` and then `python3 -m pip install .` and show me the output.

So, I'm getting different versions returned when running `python --version` (3.9.13) and `python3 --version` (3.10.11). I downloaded the python 3.9.13 Windows installer [directly from the python website](https://www.python.org/downloads/release/python-3913/). Any idea why 3.10.11 is being installed for python3? 

![image](https://user-images.githubusercontent.com/46833258/231859207-2f50280c-0b45-4cc4-8606-1acb2f6127d0.png)

**Comment by victoriawallace-cisa** [comment]
I'm not really sure why you have multiple versions of Python on your machine, but since Python 3.9.13 is installed as `python`, you could run `python -m pip install .` instead of `python3` in order to pass the Python version check. If you don't want 3.10.11 on your machine, you could always uninstall it.

**Comment by tmaiorca** [comment]
> I'm not really sure why you have multiple versions of Python on your machine, but since Python 3.9.13 is installed as `python`, you could run `python -m pip install .` instead of `python3` in order to pass the Python version check. If you don't want 3.10.11 on your machine, you could always uninstall it.

I was able to install Goose tool by running `python -m pip install .` since this referenced the 3.9.13 version, as opposed to running `python3 -m pip install .` which presumably references the 3.10.11 version.

I'm not sure why python 3.10.11 is getting installed alongside the 3.9.13 installer. In fact, it's not showing as being installed in the control panel or via WMI.  

Thanks for your help!
