### ISSUE TITLE
UN/PW Question/Idea

### ISSUE THREAD

**Issue by bbhorrigan** [cisagov/untitledgoosetool#3]
I've been playing with the tool this afternoon, and it seems pretty well put together. Great job! do you know if you have plans or ideas to deal with having the username and password in the .conf and .d4iot_conf files? Maybe some type of OAuth or secret authentication that would allow me to not have to store those credentials. Maybe some type of guide that explains how to hash them? In the Gov Space, we are not allowed to store passwords in clear text.

Thank you for putting the work into this tool.

What is the work, as a high-level summary?

Update authentication method so that we can remove the need to store UN/PW in clear text.

Why does this work belong in this project?

N/A

## Implementation notes ##

N/A

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Criterion

**Comment by victoriawallace-cisa** [comment]
Thank you for bringing this up. We're currently looking into the best way to implement the request.

**Comment by bbhorrigan** [comment]
Appreciate the time, good job on the tooling.

**Comment by MBstatsara** [comment]
Just adding a note as I wont be entering usernames/passwords into a plain text file.
If we prompted like the usual for token access (web authentication) that would be fine!

**Comment by Pavel-Sushko** [comment]
> I've been playing with the tool this afternoon, and it seems pretty well put together. Great job! do you know if you have plans or ideas to deal with having the username and password in the .conf and .d4iot_conf files? Maybe some type of OAuth or secret authentication that would allow me to not have to store those credentials. Maybe some type of guide that explains how to hash them? In the Gov Space, we are not allowed to store passwords in clear text.
> 
> Thank you for putting the work into this tool.
> 
> What is the work, as a high-level summary?
> 
> Update authentication method so that we can remove the need to store UN/PW in clear text.
> 
> Why does this work belong in this project?
> 
> N/A
> 
> ## Implementation notes
> N/A
> 
> ## Acceptance criteria
> How do we know when this work is done?
> 
> * [ ]  Criterion

+1 on this

**Comment by sbailey8800** [comment]
Agree with comments above, I was pretty excited to use this tool but not if I have to store username and passwords in cleartext.

**Comment by victoriawallace-cisa** [comment]
Hello, the feature has been added. Please let us know if this is what you are looking for.

**Comment by bbhorrigan** [comment]
Fantastic add, good job, this is working as intended.
