### ISSUE TITLE
goosey auth, error browser binary location

### ISSUE THREAD

**Issue by jpeacblth** [cisagov/untitledgoosetool#32]
# 🐛 Summary #

When I run the 'goosey auth' command i get an "...Expected browser binary location..." error

## To reproduce ##
(Windows)
1. Clone repo
2. run `python -m pip install .`
3. run `python scripts/generate_conf.py`
4. update .auth
5. run `goosey auth`
6. ran the `webdrivermanager firefox:v0.32.0 --linkpath AUTO`
7. run `goosey auth`

## Expected behavior ##

that the account creds would be checked

## Any helpful log output or screenshots ##

Paste the results here:

````2023-05-01 16:41:52,210 - auth - INFO - Could not read current authfile: [Errno 2] No such file or directory: '.ugt_auth'
This is normal if this is your first time running auth. (auth.py:705)
2023-05-01 16:41:52,632 - auth - INFO - Attempting to automatically auth via device code. You may have to accept MFA prompts. (auth.py:116)
2023-05-01 16:41:53,320 - auth - ERROR - Error getting Firefox webdriver: Message: Expected browser binary location, but unable to find binary in default location, no 'moz:firefoxOptions.binary' capability provided, and no binary flag set on the command line
. Exiting. (auth.py:61)`

```

**Comment by victoriawallace-cisa** [comment]
Where is your firefox binary located? Based on the selenium error message, it looks like its not in the Firefox default location.

Also, if you do not have Firefox, you will need install it.

**Comment by jpeacblth** [comment]
It was user error. I even read the issue with the firefox requirement, but it was not installed on the server.
