### ISSUE TITLE
Symantec VIP MFA

### ISSUE THREAD

**Issue by ninex3** [cisagov/untitledgoosetool#35]
# 💡 Summary #

To allow Symantec VIP MFA security codes

## Motivation and context ##

Allow additional MFA options (Symantec VIP).

## Implementation notes ##

Allow user(s) to enter security code obtained from app into the CLI when authenticating

## Acceptance criteria ##

Able to use Symantec VIP MFA security code to authenticate

**Comment by victoriawallace-cisa** [comment]
Hello, what happens if you try the latest version of the Untitled Goose Tool (with OTP support) with this requested MFA method? It should work if it's OTP.

**Comment by victoriawallace-cisa** [comment]
Closing this issue out as no response has been given.
