### ISSUE TITLE
Add a packaged github release

### ISSUE THREAD

**Issue by debruyne96** [cisagov/untitledgoosetool#36]
Some large organizations have automated scanning of open source tools to approve them for use within the org. Packaging the release into the Github "Release" area allows the tool to download and scan it, due to limitations of the tool we cannot scan this package due to it not having a release. 

ScubaGear has a release so I was able to scan that one, if you could package it similarly to that it would be a great help!.

**Comment by victoriawallace-cisa** [comment]
We'll look into it for a future release.

**Comment by victoriawallace-cisa** [comment]
@debruyne96 Hello! We just made a release for v1.2.1. Is this what you were looking for?

**Comment by debruyne96** [comment]
Yes thank you!!On Jun 6, 2023, at 3:25 PM, victoriawallace-cisa ***@***.***> wrote:﻿
@debruyne96 Hello! We just made a release for v1.2.1. Is this what you were looking for?

**Comment by victoriawallace-cisa** [comment]
Thanks, I'll go ahead and close out this issue then.
