### ISSUE TITLE
Add Firefox as a required pre-requisite

### ISSUE THREAD

**Issue by born-slippy** [cisagov/untitledgoosetool#4]
# 💡 Summary #

What is the work, as a high-level summary?

Add Firefox as a required pre-requisite in documentation

## Motivation and context ##

Why does this work belong in this project?

Its a requirement

This would be useful because...

Having an accurate list of pre-requisites is helpful

## Implementation notes ##

Please provide details for implementation, such as:

- an example for how this would be used
- what this would look like
- how this would act
- any related work, including links to related issues

## Acceptance criteria ##

How do we know when this work is done?

- [ ] Criterion

**Comment by victoriawallace-cisa** [comment]
Hi, I'll incorporate this fix in a pull request and close this issue out.
