### ISSUE TITLE
Allow for refreshing auth token while collecting data via honk

### ISSUE THREAD

**Issue by lautriv** [cisagov/untitledgoosetool#58]
# 💡 Summary #

It would be wonderful if the team could refactor the collection functions to allow for refreshing tokens during `goosey honk`. 

## Motivation and context ##

When performing a collection via `honk` on a large tenant it is common for the authentication token to expire prior to the completion of collection. E.g.

```
2023-10-06 19:32:36,067 - azure_ad_datadumper - ERROR - Error with authentication token: Lifetime validation failed, the token is expired. (azure_ad_datadumper.py:399)
2023-10-06 19:32:36,067 - azure_ad_datadumper - ERROR - Please re-auth. (azure_ad_datadumper.py:400)
```

While a user could collect items individually by modifying `.conf` and repeatedly running `honk`, I don't think that is sustainable in the long term. 

## Implementation notes ##

I would expect that `honk` (and the underlying modules) will need to have functionality added to be able to:
- Detect when a token has expired
- Pause collection 
- Re-prompt the user for authentication
- Resume collection once a new token has been received

Alternatively, we might be able to use refresh tokens assuming those are available for the application authentication flows.

## Acceptance criteria ##

How do we know when this work is done?

- [ ] `honk` is able to detect when an authentication token has expired
- [ ] `honk` will request a new authentication token and resume collection

**Comment by AuthMon** [comment]
This would be a great feature for use in larger tenants where execution can take several hours.
The current build looks for 429 response from graph API and terminates after an hour of execution with a message asking for re-auth.

**Comment by nkantor-snl** [comment]
The newest version of the tool has moved to authentication through service principal only. This more easily allows the tool to refresh auth tokens since user auth with MFA is no longer integrated. If you would like to do this for your use of the tool please checkout the documentation on autohonk in the [README](https://github.com/cisagov/untitledgoosetool/blob/develop/README.md)
