### ISSUE TITLE
Interest in containerization

### ISSUE THREAD

**Issue by corbin-lounsbury** [cisagov/untitledgoosetool#59]
# 💡 Summary #

What is the work, as a high-level summary?

Trying this out at work and I wanted to see if there was interest in containerizing the application to make installation and use easier

Why does this work belong in this project?

As stated above, it would be easier to resolve dependencies and provide a way to run regardless of platform

## Implementation notes ##

Still working this out. I have a somewhat working version, but wanted to check if someone else had done it or if there wasn't any interest in maintaining it. Also wanted to inquire about logistics like if CISA had it's own Docker space to publish and what sort of tests or scans were needed. 

## Acceptance criteria ##

- [ ] Application is installed and running as intended on a container.

**Comment by nkantor-snl** [comment]
Containerization was added in the 2.0.1 release of the tool. You can find the [Dockerfile here](https://github.com/cisagov/untitledgoosetool/blob/develop/Dockerfile) and the [documentation for it here](https://github.com/cisagov/untitledgoosetool/blob/develop/README.md)

To build and run use the following commands

```
docker build . -t goosey
docker run -it -v $PWD:/workdir goosey goosey honk --debug
```
