### ISSUE TITLE
`No module named 'blinker._saferef'` error when running `generate_conf.py`

### ISSUE THREAD

**Issue by el-pato** [cisagov/untitledgoosetool#62]
# 🐛 Summary #

When running `python3 scripts/generate_conf.py`, the following error occurs: `ModuleNotFoundError: No module named 'blinker._saferef'`

## To reproduce ##

1. Follow set up instructions and run `python3 scripts/generate_conf.py`

## Expected behavior ##

Config file should have been generated, instead got an error.

## more info
This appears to be an issue with selenium. See this issue for more details: https://github.com/seleniumbase/SeleniumBase/issues/2782

Per that thread, I manually did `pip install blinker==1.7.0` and was then able to generate the config file.

**Comment by nkantor-snl** [comment]
This script has been removed in the latest release of the tool and is no longer an issue. Thank you!
