### ISSUE TITLE
Also investigate if other forms of managed identity (federation, etc) would also work through this addition or if it would required additional changes.

### ISSUE THREAD

**Issue by Azile89** [cisagov/untitledgoosetool#63]
Also investigate if other forms of managed identity (federation, etc) would also work through this addition or if it would required additional changes.

Connect-ExchangeOnline -ManagedIdentity -Organization contoso.onmicrosoft.com Elizamrse@gmail.com/elizamybackyardcustoms@outlook.com

**Comment by nkantor-snl** [comment]
Not super clear what this issue is referencing. Exchange Online association of the goose tool service principal is done now through the [setup script](https://github.com/cisagov/untitledgoosetool/blob/develop/scripts/Create_SP.ps1) in the latest goose version. Closing this issue for now.
