### ISSUE TITLE
No module named goosey

### ISSUE THREAD

**Issue by santiago1976** [cisagov/untitledgoosetool#8]
# 🐛 Summary #

What's wrong? Please be specific.

## To reproduce ##

1. Do this
1. Then this

## Expected behavior ##

What did you expect to happen that didn't?

## Any helpful log output or screenshots ##

Paste the results here:

```console

```

Add any screenshots of the problem here.

**Comment by santiago1976** [comment]
When I try to execute python3 scripts/generate_conf.py in Windows cmd, I always obtain: No module named 'goosey'

How can I fix it?

Thanks

**Comment by victoriawallace-cisa** [comment]
Hi, thank you for submitting this issue. Did you install the tool using the following commands before running the generate_conf.py:

```
git clone https://github.com/cisagov/untitledgoosetool.git
cd untitledgoosetool
python3 -m pip install . 
```

**Comment by RP5406** [comment]
While running the commands:
git clone https://github.com/cisagov/untitledgoosetool.git
cd untitledgoosetool
python3 -m pip install . 

ERROR: Package 'goosey' requires a different Python: 3.10.6 not in '<3.10,>=3.7'

**Comment by victoriawallace-cisa** [comment]
> While running the commands: git clone https://github.com/cisagov/untitledgoosetool.git cd untitledgoosetool python3 -m pip install .
> 
> ERROR: Package 'goosey' requires a different Python: 3.10.6 not in '<3.10,>=3.7'

You'll need to downgrade your Python version to Python 3.7, 3.8, or 3.9.

**Comment by santiago1976** [comment]
Yes, of course

**Comment by victoriawallace-cisa** [comment]
Did you receive any errors when doing the pip install? Can you share the output of your pip install?

**Comment by MBstatsara** [comment]
Can you confirm we are only using old vulnerable version of Python to report on 365 environments?
i will have to create an "unsupported" VM to install this on, as python 3.9, hasn't been updated or available as an install for sometime!

**Comment by RP5406** [comment]
` Traceback (most recent call last):

        File "<string>", line 36, in <module>

        File "<pip-setuptools-caller>", line 34, in <module>

        File "/tmp/pip-install-qm_e7n5z/wxpython_9db148af8a4d470f892b72d08a77647a/setup.py", line 27, in <module>

          from buildtools.config import Config, msg, opj, runcmd, canGetSOName, getSOName

        File "/tmp/pip-install-qm_e7n5z/wxpython_9db148af8a4d470f892b72d08a77647a/buildtools/config.py", line 30, in <module>

          from attrdict import AttrDict

      ModuleNotFoundError: No module named 'attrdict'

      [end of output]`

**Comment by victoriawallace-cisa** [comment]
> Can you confirm we are only using old vulnerable version of Python to report on 365 environments? i will have to create an "unsupported" VM to install this on, as python 3.9, hasn't been updated or available as an install for sometime!

wxpython doesn't work with Python versions above 3.9. If you are on Python 3.10, the setup won't work properly. Technically, according to Python (https://devguide.python.org/versions/), 3.9 is still supported and security fixes are still being implemented.

**Comment by RP5406** [comment]
I tried with python 3.9 and 3.7 see error above.

**Comment by victoriawallace-cisa** [comment]
> I tried with python 3.9 and 3.7 see error above.

Are you on *nix? Are you calling the correct Python version? Could you post the entire output?

**Comment by santiago1976** [comment]
Hello,

downgrading Python from 3.10 to 3.9 it's working fine

Thanks

**Comment by victoriawallace-cisa** [comment]
Thank you, I'll go ahead and resolve this issue.
